### ISSUE TITLE
`GetNextNonInclusive` returns incorrect value under boundary conditions

### ISSUE THREAD

**Issue by emptierset** [FireFox2000000/Moonscraper-Chart-Editor#101]
This almost certainly also applies to `GetPreviousNonInclusive`, but I did not test it.

Scenario: `GetNextNonInclusive` is called with `songObjects=[BPM(position=0), BPM(position=1000)]` and `position=1000`.
Expected behavior: `GetNextNonInclusive` returns `null`.
Observed behavior: `GetNextNonInclusive` returns `BPM(position=1000)`.

I have reproduced the function's code below for convenience:

```cs
public static T GetNextNonInclusive<T>(IList<T> songObjects, uint position) where T : SongObject
{
    int pos = GetIndexOfNext(songObjects, position);
    if (pos != NOTFOUND)
    {
        if (songObjects[pos].tick == position && pos < songObjects.Count - 1)
            ++pos;

        return songObjects[pos];
    }
    else
        return null
}
```

The following code block demonstrates the correct behavior:

```cs
public static T GetNextNonInclusive<T>(IList<T> songObjects, uint position) where T : SongObject
{
    int pos = GetIndexOfNext(songObjects, position);
    if (pos != NOTFOUND)
    {
        if (songObjects[pos].tick == position)
        {
            if (pos >= songObjects.Count - 1)
                return null
            ++pos;
        }

        return songObjects[pos];
    }
    else
        return null
}
```

(and I'd probably rewrite it like this, given the chance):

```cs
public static T GetNextNonInclusive<T>(IList<T> songObjects, uint position) where T : SongObject
{
    int pos = GetIndexOfNext(songObjects, position);
    if (pos == NOTFOUND)
        return null;

    if (songObjects[pos].tick == position)
    {
        ++pos;
        if (pos >= songObjects.Count)
            return null;
    }

    return songObjects[pos];
}
```

**Comment by FireFox2000000** [comment]
Is there are actual functionality issue that is resulting from this behaviour?

**Comment by emptierset** [comment]
No idea. I ran into it working on my personal fork of the program. It's just obviously incorrect behavior, so there may be some logic that assumes this function works as it claims to.

**Comment by FireFox2000000** [comment]
Won't fix, no explicit functionality issue.
