### ISSUE TITLE
Cant Separate 5 Lane Drums from Pro Drums

### ISSUE THREAD

**Issue by PixelGaming123** [FireFox2000000/Moonscraper-Chart-Editor#102]
I am not sure what i am meant to do to make them separated but i am trying to make a chart that is compatible with both but i keep running into issues where they conflict with eachother because its modifying both at the same time. i would like to know what i am meant to do to make them separated so that i can individually modify each.

**Comment by FireFox2000000** [comment]
This is not possible as Clone Hero/other GH games store 4/5/Pro Drums data all in the same track.
