### ISSUE TITLE
Can't change offset in 1.3.1

### ISSUE THREAD

**Issue by maximmax42** [FireFox2000000/Moonscraper-Chart-Editor#11]
Hello. This version of Moonscraper completely ignores anything about offset property. Open any chart file and the song properties show 0 on the offset, even if it's not actually 0. Changing it there and reopening properties window - still stays 0. Entering offset and hitting save without closing - saves 0 into the file.

My guess it's to do with the culture checking, since our country uses commas as separators, but that brings another problem - you can't put a comma into the field.

Edit: Changed decimal separator in system settings - nop, didn't help. Asked someone else who is on English Windows - apparently there are no problems.
Edit 2: Changing offset to an integer amount works fine, but as soon as you put anything other than integer it drops to 0.

**Comment by FireFox2000000** [comment]
Has been fixed and should work in the next test build/official release.
