### ISSUE TITLE
Linux x86-64: Doesn't detect required dependencies even when installed

### ISSUE THREAD

**Issue by JapanYoshi** [FireFox2000000/Moonscraper-Chart-Editor#110]
![but theyre installed tho](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/assets/8707990/cf9d3442-bf36-4fa7-88d7-94c04072a89f)

Booting the program on Linux Mint displays this error message and quits. However, all the packages it asked for have been installed already.

**Comment by FireFox2000000** [comment]
Could you try installing "libsdl2-dev" as well to see if that fixes it?

**Comment by ntvmb** [comment]
> Could you try installing "libsdl2-dev" as well to see if that fixes it?
I had the same issue OP was having (on Debian) and I tried this solution and that solved the problem

**Comment by JapanYoshi** [comment]
That seems to have fixed it!
