### ISSUE TITLE
Moonscraper issue

### ISSUE THREAD

**Issue by tieplemaginoio** [FireFox2000000/Moonscraper-Chart-Editor#111]
I have got an issue like that, can you help me to solve this problem? I can't save file and upload on beatstar encrypted, can anyone help me? Thank you so much

![image](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/assets/141126225/60ea7783-6aeb-4dda-88e9-33990e104077)

**Comment by FireFox2000000** [comment]
Could you describe you took to encounter the error? And provide and files (such as charts) that could help in reproducing the issue?

**Comment by tieplemaginoio** [comment]
While I was creating a chart on Moonscraper, it noticed error like the
image I have upload, It remine me to report "Appdata..." but I do not
understand what to do. When I pressed continue to do, it once again noticed
error, when I pressed No, it closed. I restart PC and download a new
version, it once again appeared this error. Especially, I couldn't save the
file that I did and it can't upload on beatstar encrypted
Can you help me solve this problem? I need to creat a custom song on
Beatstar.
Thank you so much

[image: image.png]

Vào Th 5, 3 thg 8, 2023 vào lúc 15:54 FireFox2000000 <
***@***.***> đã viết:

**Comment by FireFox2000000** [comment]
Could you be more a lot more specific than "creating a chart"? I will need to know how to reproduce the issue step-by-step on my side in order to figure out the cause of the issue. If you could record a video of the actions you took from first opening Moonscraper to hitting the issue that would be helpful as well.

**Comment by tieplemaginoio** [comment]
Do you chat on discord, my file MP4 that I can't send to you because it is
very large

Vào Th 6, 4 thg 8, 2023 vào lúc 04:29 FireFox2000000 <
***@***.***> đã viết:

**Comment by FireFox2000000** [comment]
Discord file limits probably won't help with that either. You can upload a video to youtube unlisted and then send a link here, or upload it to something like google drive or dropbox and I can download it that way via a public link.

**Comment by tieplemaginoio** [comment]
That is a good idea. I send to you the link of the video
Thank you very much.
https://drive.google.com/file/d/1-ogIDWIs-T1Agbh-qC5vgRK5MbTfX1Xr/view?usp=drive_link


Vào Th 6, 4 thg 8, 2023 vào lúc 18:52 FireFox2000000 <
***@***.***> đã viết:

**Comment by FireFox2000000** [comment]
Could you also provide me a link to the chart file and audio that was used in the video? Trying to replicate it without that doesn't appear to run into the issue. 
Also do you happen to know what you did after you pressed "u" in the video? Like did you enter another key, add a space or hit backspace or delete etc.

**Comment by tieplemaginoio** [comment]
I send you 2 file, they are a chart file and a wave file

https://drive.google.com/drive/folders/1a7MvfhAoa9MVcL5qA1Pwa5a28p4mUMLS?usp=sharing


Vào Th 7, 5 thg 8, 2023 vào lúc 06:25 FireFox2000000 <
***@***.***> đã viết:

**Comment by FireFox2000000** [comment]
Hm, I'm still unable to replicate any error on my end, even with the files you've provided. Does this issue happen consistently for you when you do the same thing in the video? Also do you happen to know what you did after you pressed "u" in the video? Like did you enter another key, add a space or hit backspace or delete etc.

**Comment by tieplemaginoio** [comment]
I press "ur2" to creat a swipe on beatstar, when I press "r", it appears
error and it is always like this when I use another computer. Therefore, I
am not able to continue

Vào CN, 6 thg 8, 2023 vào lúc 19:06 FireFox2000000 <
***@***.***> đã viết:

**Comment by tieplemaginoio** [comment]
Before, moonscraper works well when I do like this, I can not understand
what the problem is

Vào Th 2, 21 thg 8, 2023 vào lúc 23:12 Tiệp Lê ***@***.***> đã
viết:

**Comment by tieplemaginoio** [comment]
please help me

**Comment by tieplemaginoio** [comment]
![image](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/assets/141126225/207008d0-db3c-468a-b06d-b22e32502390)

**Comment by FireFox2000000** [comment]
I have finally managed to reproduce this, looks like a consistent way is to spam inputs and backspace into the textbox. Sometimes this leads to it deselecting the events, sometimes it leads to this error.

**Comment by FireFox2000000** [comment]
Fixed at https://github.com/FireFox2000000/Moonscraper-Chart-Editor/commit/3e0f2782670221eeb1a1c48e47305538d5940d23
