### ISSUE TITLE
Mesh cannot have more than 65000 vertices

### ISSUE THREAD

**Issue by imvr17** [FireFox2000000/Moonscraper-Chart-Editor#115]
I tried to save and a window popped up saying there was an unexpected error and didn't let me save

[output_log.txt](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/files/12433185/output_log.txt)

**Comment by FireFox2000000** [comment]
Fixed as per- https://github.com/FireFox2000000/Moonscraper-Chart-Editor/commit/cc796a8c774b7073b78e69bf87d8bf3458aa39c1
