### ISSUE TITLE
Red cursor does not snap to the grid when changing the tempo and/or time signatures

### ISSUE THREAD

**Issue by utybo** [FireFox2000000/Moonscraper-Chart-Editor#12]
The red cursor does not snap to the grid correctly when changing the tempo/time signature midway

Using this setup at the beginning of the chart

![image](https://user-images.githubusercontent.com/5175705/58832399-243c9800-864f-11e9-8ba1-5920e4438b9d.png)

Results in this after the second BPM marker (the BPM 75 one you can see in the screenshot). Using the 1/24 step setting, it puts the red cursor either before or after the bar.

![image](https://user-images.githubusercontent.com/5175705/58832476-49310b00-864f-11e9-8083-c00588080c1a.png)

![image](https://user-images.githubusercontent.com/5175705/58832558-78477c80-864f-11e9-9283-81109d701879.png)

Here is the .chart file (you can ignore the notes)

[Interluden.zip](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/files/3249371/Interluden.zip)

The issue is particularly visible when using the 1/24 and 1/12 step settings.

Edit: note that I am changing the tempo multiple times in the song, that seems to be problematic

**Comment by utybo** [comment]
I have fixed it, the line which I found was indeed the culprit. I will be uploading a PR soon :tm:

For the record: time signature changes are supposed to be placed on **measures** only: even if they're shown properly in Moonscraper, they won't show up in Clone Hero. This fix still works in situations like having a 9/16 measure followed by a 4/4 measure. (thanks XEntombmentX for the example!)

**Comment by FireFox2000000** [comment]
Fixed with commit "Step/snap placement now relative to the beat lines instead of internal tick layout". Pull request does not fully correct the issue and lacks the use of optimised lookup functions already provided in the code.
