### ISSUE TITLE
No Support for Foreign Characters

### ISSUE THREAD

**Issue by Mortisanti** [FireFox2000000/Moonscraper-Chart-Editor#15]
...at least in the loading_phrase text. For example, in [this image](https://i.imgur.com/aanybRh.png) the missing character between "D" and "d" is supposed to be ø, the Nordic o with a slash. I would like to see support added for foreign characters in Moonscraper.

**Comment by FireFox2000000** [comment]
This is an issue with Clone Hero. Re-open if you can get these characters to appear in Clone Hero without the use of Moonscraper.
