### ISSUE TITLE
Unity Project in Mac Error

### ISSUE THREAD

**Issue by Taurustar** [FireFox2000000/Moonscraper-Chart-Editor#17]
<img width="914" alt="Screen Shot 2019-09-02 at 5 01 53 PM" src="https://user-images.githubusercontent.com/3971084/64133337-65099180-cda3-11e9-8290-c5e385869252.png">

Hello, I'm having the next issue when I tried to open the project in Unity Editor using a Mac. I'd like to make some port but I don't know how to solve this problem... If you could give me a hint I could probably port this to a Mac Unity Project or at least be usable in the Unity Editor for Mac Developers

Regards

**Comment by FireFox2000000** [comment]
Was a preprocessor define error that wasn't commented out correctly. Fixed and pushed.
