### ISSUE TITLE
Right Ctrl doesn't work

### ISSUE THREAD

**Issue by JapanYoshi** [FireFox2000000/Moonscraper-Chart-Editor#18]
I had issues with copying and pasting. I couldn't figure out what the problem was until I tried each of the Ctrl keys, and found out that only the left Ctrl key did anything.

**Comment by FireFox2000000** [comment]
Could you post which version you're using? Right-ctrl works fine for me in v1.3.1.1.

**Comment by JapanYoshi** [comment]
Never mind, updated to 1.3.1.1 and right Ctrl works now.
