### ISSUE TITLE
Display global events horizontally rather than vertically

### ISSUE THREAD

**Issue by evanw555** [FireFox2000000/Moonscraper-Chart-Editor#19]
It's really hard to read and edit global events when there are many of them close together (e.g. song lyrics). They all overlap and it's impossible to read them and edit them.

Is there any way they can be displayed in a different way? Like perhaps horizontally rather than vertically? Maybe this can be a configurable option.

Not sure how easy this is to do. If you don't have time, I can try to open a PR myself.

**Comment by evanw555** [comment]
It looks like you added a "lyric editor" tool a couple weeks back (commit: 04a576b81aeb5508f6938f550774e35806b1d759). Is this something that will solve this problem? Perhaps I'll clone the repo and test it out when I get home.

On a similar note: when do you think the next release will be?

**Comment by FireFox2000000** [comment]
Been meaning to redo the visual aspect of events for ages now anyway. Lyric editor was purely experimental and needs revisiting. 
Implemented with 8e7a4eb05e388d42749a6b3a743cd2eedcd89e2c
