### ISSUE TITLE
.chart format

### ISSUE THREAD

**Issue by AsLogd** [FireFox2000000/Moonscraper-Chart-Editor#21]
Hey. Congratulations on the Moonscraper tool. It's awesome. 
I was wondering if there is any kind of resource to understand the .chart format. I would like to try and make a chart player just for fun.

**Comment by FireFox2000000** [comment]
Just finished writing one up as it seems there currently isn't any solid documentation for it and we'll need to document some stuff for some new Clone Hero features soon. Still going through a proof-reading phase to make sure everything is accurate, but you can check it out here- https://docs.google.com/document/d/1v2v0U-9HQ5qHeccpExDOLJ5CMPZZ3QytPmAG5WF0Kzs/edit?usp=sharing

**Comment by AsLogd** [comment]
Exactly what I was looking for. Thank you!
