### ISSUE TITLE
Using a negative song offset should pad the end of the charting area

### ISSUE THREAD

**Issue by matrefeytontias** [FireFox2000000/Moonscraper-Chart-Editor#22]
This makes it so stuff like this can happen. The song's audio file ends pretty abruptly, so using a -2.4 seconds song offset makes the end of the song unreachable.

![image](https://user-images.githubusercontent.com/3048928/79076364-d4604000-7cf9-11ea-9975-91ff223a972c.png)

**Comment by FireFox2000000** [comment]
Fixed with commit 56cb8ebde2eab26843b82827d444d126f23699e8
