### ISSUE TITLE
Offset problems on a non-English system (again)

### ISSUE THREAD

**Issue by maximmax42** [FireFox2000000/Moonscraper-Chart-Editor#23]
Hello, it's me again from the ussue #11 

My Windows is in Russian, and since Mooscraper uses locale settings for separators (apparently), it only allows to input a comma there, yet that leads to a number of problems:
- While it does save the value now (unlike before), CH just doesn't care about the decimal part of the offset if it's separated with a comma, it wants a dot.
- If you try to load any chart with an offset that does use a dot in the .chart file, MS doesn't load it and any parameters after (Resolution, Player2, Difficulty, Genre, MediaType, MusicStream), using default ones instead.
- If you try to open up a .chart with the comma-separated offset value, it ignores the decimal part, but does keep the int part.

**Comment by FireFox2000000** [comment]
Hopefully fixed. Give this test build a whirl and see if it works. Should've only been saving with the full-stop decimal point in the first place. 

https://drive.google.com/open?id=1eV14F3DZLVoBzfVcycKWspBVWSjf2Ym7

**Comment by maximmax42** [comment]
All 3 problems still exist.

**Comment by FireFox2000000** [comment]
So just to clarify, when saving out a chart Moonscraper is saving offset in the format Offset = 0,5, instead of Offset = 0.5?

**Comment by maximmax42** [comment]
Yep, exactly that.

**Comment by FireFox2000000** [comment]
Try out this one- https://drive.google.com/open?id=1WnaovXBS6BEzonrd-GDU1s1dYyGNlF_3

**Comment by maximmax42** [comment]
Now it does save with a period instead of a comma, but other 2 problems (defaults half of properties with a period and ignores decimal part with a comma) are still a thing.

**Comment by FireFox2000000** [comment]
I'm not sure I understand? It's not valid for .chart to have commas as decimal separators in the first place. Are you saying there are other properties being written out with a comma or something?

**Comment by maximmax42** [comment]
No, no, everything is saving correctly now, I was just checking if it would parse a chart file with comma correctly (in case someone would open a file generated by an unfixed version in a fixed one). It's not critical really, just a nice to have for backwards compatibility.

**Comment by FireFox2000000** [comment]
Ah okay. I'm not going to worry about that. Offset isn't something that's recommended to be used in the first place as it's a very old legacy option, so this would be have affected very few users/charts. Sounds like the issue is fixed then. Feel free to use this test build until the next official release.

**Comment by maximmax42** [comment]
Wait wait wait, what about other problem, half the properties doesn't load from the correctly formatted file.

**Comment by FireFox2000000** [comment]
Can you be specific about which properties and provide an example .chart?

**Comment by maximmax42** [comment]
Any .chart file with non-integer offset value; upon opening it, Offset, Resolution, Player2, Difficulty, PreviewStart, PreviewEnd, Genre, MediaType, and MusicStream (or whatever happens to be under Offset in the file within [Song] section) get reset.

**Comment by FireFox2000000** [comment]
Loading a song with Offset 0.5 works fine for me.

**Comment by maximmax42** [comment]
Not on PC currently, but I remember investigating it, and loading same chart but with decimal part of the offset removed in a text editor it loaded just fine.

**Comment by maximmax42** [comment]
Was able to recreate with a blank project.
https://www.youtube.com/watch?v=mmy9LonsG6M
```
[Song]
{
  Name = "123"
  Artist = "123"
  Charter = "123"
  Album = "123"
  Year = ", 123"
  Offset = 0.1
  Resolution = 192
  Player2 = bass
  Difficulty = 3
  PreviewStart = 0
  PreviewEnd = 0
  Genre = "123"
  MediaType = "123"
  MusicStream = "song.ogg"
}
[SyncTrack]
{
  0 = TS 4
  0 = B 120000
}
[Events]
{
}
```

**Comment by FireFox2000000** [comment]
Managed to recreate the issue by changing the application's locale on startup. Issue has been fixed and will be available in the next release, or the next test build if you're a part of the MS Discord. If you need a build sooner for any charts you're currently working on let me know and I'll drop another download link into this thread in the next day day or so.
