### ISSUE TITLE
Solo sections can get lost in the conversion from .mid to .chart

### ISSUE THREAD

**Issue by GenericMadScientist** [FireFox2000000/Moonscraper-Chart-Editor#24]
[This Sweating Bullets .mid file](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/files/4486762/sweating-bullets.zip) has a solo section when played in Clone Hero, but if you open it in Moonscraper and save it as a .chart the solo section is lost.

**Comment by FireFox2000000** [comment]
Fixed and will be available in the next release.
