### ISSUE TITLE
Clap function not working with music

### ISSUE THREAD

**Issue by robertfields32** [FireFox2000000/Moonscraper-Chart-Editor#26]
It appears that the song audio is overriding the clap sound. When I remove the song audio, the clap will play. But when I add it back, the clap doesn't play.

**Comment by robertfields32** [comment]
Additionally, this is only occurring in the x64 version of the software

**Comment by robertfields32** [comment]
That didn't take long to figure out. On both x86 and x64, the clap function will not work if you set the audio offset to anything but zero.

**Comment by FireFox2000000** [comment]
Appears to only be an issue with negative offset values. Although clap position seems to be being affected by offset when it shouldn't in the first place.

**Comment by FireFox2000000** [comment]
Fixed with commit f84c4f18ac647b0ccc09958650526259c747e26b
