### ISSUE TITLE
Moonscraper Chart Editor v1.3.3.2 doesn't allow Open Notes.

### ISSUE THREAD

**Issue by Enrier** [FireFox2000000/Moonscraper-Chart-Editor#27]
For some reason, you're unable to set open notes in this version, when pressing 6. 
While Moonscraper Chart Editor v1.3.3.1 lets you do it.

**Comment by FireFox2000000** [comment]
This was mentioned in the changelog as well as the video overview outlining this change. Open note key was moved from '6' to '0' in order to support rebindable control functionality.
