### ISSUE TITLE
[Feature request] More than 5 colors on chart editor.

### ISSUE THREAD

**Issue by ebellumat** [FireFox2000000/Moonscraper-Chart-Editor#29]
Hello! I'm a game developer that is creating an a Guitar Hero like drum game for Oculus Quest, i prettend to use Moonscraper-Chart-Editor as official chart editor for the game, but, my planned drum kit have 7 itens instead of 5.

You can check out some details here. [Reddit Post](https://www.reddit.com/r/OculusQuest/comments/gqobi5/charting_prototype_of_drum_rhythm_game_for_oculus/).

Can you add this feature? Or, can i fork and add this feature?

**Comment by FireFox2000000** [comment]
Moonscraper currently supports up to 6 lanes for GHL, it wouldn't be overly difficult to add an extra lane to make 7 possible but I'm not going to implement it in Moonscraper as that's not within the scope of what Moonscraper is intended for at this time, as no GH-style game that's directly supported (GH3, Clone Hero) utilises a 7th lane in their gameplay. You're better off making a fork and adding the 7th lane in a private repro.
