### ISSUE TITLE
Feature request (XInput support)

### ISSUE THREAD

**Issue by Sellis97** [FireFox2000000/Moonscraper-Chart-Editor#3]
It would be awesome if Moonscraper got XInput support so we could chart with guitars.
The charting progress would be a lot faster and more user friendly. There are more benefits like getting the tempo synced with much less sweat and creating more complex and catchy combos with ease. 
This would be a huge help too when experimenting with different approaches how a part of the song should be played.

**Comment by FireFox2000000** [comment]
Guitar compatibility is restricted to only gameplay mode. Allowing free-form charting has the tendency for people to ignore tempomapping properly and result is poor quality charts. This particular request has already been discussed as such in the Discord server.
