### ISSUE TITLE
[Feature Request] 2 more lanes to support Beat Smith.

### ISSUE THREAD

**Issue by ebellumat** [FireFox2000000/Moonscraper-Chart-Editor#37]
Hello! I'm a game developer that is creating an a Guitar Hero like Drum game for Oculus Quest, i prettend to use Moonscraper-Chart-Editor as official chart editor for the game, but, my planned drum kit have 7 itens instead of 5.

The name of the game is Beat Smith, and i plan to release on Oculus Store before Christmas.

I forked the chart editor, but i found a lot of dificulties to add 2 more lanes...

Can you add this feature? Or can you explain me how to do this?

**Comment by ebellumat** [comment]
This is the prototype working.

https://youtu.be/l-cy6NwYqHU

**Comment by FireFox2000000** [comment]
Moonscraper already handles this with the "Pro Drums" mode when editing a drums chart using cymbal/tom toggles. You can read more about it here- http://docs.c3universe.com/rbndocs/index.php?title=Drum_Authoring#Displaying_Tom_Gems

If you need to have cymbals and toms of the same colour at the same time, or new types of notes etc, then you're better off using a dedicated MIDI editor like Reaper.

**Comment by ebellumat** [comment]
And how can i see the cymbal/toms on Pro-Mode? What's the shortcut key to toggle this? 

I think this will fit perfectly. 

Thanks for you explanation!

**Comment by FireFox2000000** [comment]
No problem.
