### ISSUE TITLE
Custom Flags with spaces

### ISSUE THREAD

**Issue by GromoZavr** [FireFox2000000/Moonscraper-Chart-Editor#39]
I am using custom flags with spaces for making charts for my game that looks like "K 21 78 56 13" but Moonscraper doesn't process them properly. Could you add the following change to the file \Assets\Scripts\Game\Charts\IO\Chart\ChartReader.cs

LINE 684: 
string eventName = line.Substring(stringStartIndex, stringLength);

CHANGE TO:
string eventName = line.Substring(stringStartIndex, line.Length - stringStartIndex);

This will not affect the rest of the functionality, but add support for flags with spaces.

**Comment by FireFox2000000** [comment]
This goes against the .chart format spec and will not be implemented. It's recommended to use either camelcase formatting or underscores as spaces instead. Will update Moonscraper to automatically replace space characters with underscores in track events instead.
