### ISSUE TITLE
[Help] Help me understand the [SyncTrack]

### ISSUE THREAD

**Issue by ebellumat** [FireFox2000000/Moonscraper-Chart-Editor#41]
Can you translate me this part of the chart file?

This works fine.

```
[SyncTrack]
{
  0 = TS 4
  0 = B 49000
  240 = B 98000
  90240 = TS 6
  91200 = B 99000
  93120 = TS 4
  93120 = B 98000
}
```

I have some issues with songs with SyncTracks like this

```
[SyncTrack]
{
  0 = TS 4
  0 = B 120000
}
```

What info the SyncTrack of the top have that the second SyncTrack dosen't have?

Thanks, Erasmo.

**Comment by FireFox2000000** [comment]
https://docs.google.com/document/d/1v2v0U-9HQ5qHeccpExDOLJ5CMPZZ3QytPmAG5WF0Kzs/edit?usp=sharing
