### ISSUE TITLE
Difficulty is not copied into diff_guitar upon Clone Hero export

### ISSUE THREAD

**Issue by matrefeytontias** [FireFox2000000/Moonscraper-Chart-Editor#49]
Everything else from the song properties are properly copied into the song.ini file, except for the difficulty.

**Comment by FireFox2000000** [comment]
Could you note the version number of Moonscraper you're using and whether this is using the new ini editor or the defaults created when exporting a song, or some other method you're using to generate the song.ini?

**Comment by matrefeytontias** [comment]
It's the latest version, v1.4.1. Neither of those methods copy down the difficulty to the exported file when you type the difficulty in the "General" tab of the Song Properties menu.

**Comment by matrefeytontias** [comment]
Bump, new version does not fix this.
