### ISSUE TITLE
Update README to reflect actual download location for MCE

### ISSUE THREAD

**Issue by tehbasshunter** [FireFox2000000/Moonscraper-Chart-Editor#5]
The wikia page for CH links to this repo and gives the impression that Unity/this are needed to chart songs.

**Comment by FireFox2000000** [comment]
Added a separate repro for releases at https://github.com/FireFox2000000/Moonscraper-Chart-Editor-Latest-Official-Release. Will inform the editors of the wiki.

**Comment by tehbasshunter** [comment]
I totally forgot about this "issue". Definitely can consider it fixed and closed.
