### ISSUE TITLE
Opus song files are read, but not copied when exporting

### ISSUE THREAD

**Issue by matrefeytontias** [FireFox2000000/Moonscraper-Chart-Editor#50]
Upon exporting a chart that uses a `*.opus` audio file, only `notes.chart` and `song.ini` are produced.

In addition to the simple fix of actually copying the song file, a checkbox option could be added to offer converting it to `*.ogg` format as v23 is not capable of reading opus files.

**Comment by FireFox2000000** [comment]
Fixed as per referenced commit.

**Comment by matrefeytontias** [comment]
I think at the end of the day, it would be preferable to actually use Opus files instead of OGG since the latest versions of CH support them and they're both more efficient and higher quality (with the right compression settings). Would it be sensible to add that checkbox I mentioned in the original post, maybe in the Export menu ?
