### ISSUE TITLE
Unholy CPU/GPU usage

### ISSUE THREAD

**Issue by Grimtin10** [FireFox2000000/Moonscraper-Chart-Editor#53]
Moonscraper uses **all** of my CPU and GPU, at the same time running at like 3 fps. I can't use it like this. I don't even know how to fix it because there's not enough options.

**Comment by FireFox2000000** [comment]
Minimise the screen resolution by just simply making the window smaller. Also reduce anit-aliasing in the graphics options in the settings menu. If these tips don't help then your device is probably too underpowered for the app.
