### ISSUE TITLE
[Suggestion/Question] Launch in Fullscreen

### ISSUE THREAD

**Issue by lilkingjr1** [FireFox2000000/Moonscraper-Chart-Editor#59]
Is there any way to make the app launch fullscreen every time, other than using a Windows shortcut (ie. double-clicking on a `.chart` file)?

If not, could a config option be added to the UI to allow this behavior? That would be very convenient :)

**Comment by FireFox2000000** [comment]
Won't do, window title contains current session information intended to be displayed to the user at all times. Not even sure how you managed to get full-screen by double clicking a chart file in the first place.
