### ISSUE TITLE
HUGE CPU Usage While Idle

### ISSUE THREAD

**Issue by zachdwyer** [FireFox2000000/Moonscraper-Chart-Editor#6]
![image](https://user-images.githubusercontent.com/5987504/42425962-7c41f8e0-82f1-11e8-8192-11275cd77921.png)

Sometimes I have MS in the background, and suddenly my computer is just bogged down. I have a 6-core AMD Phenom II.

I have no charts loaded, just happens on a blank new chart.

**Comment by FireFox2000000** [comment]
Try limiting your framerate under the setting menu option. You might have it set to unlimited fps.
