### ISSUE TITLE
Issue with Moonscraper on Linux

### ISSUE THREAD

**Issue by c291bGxlc3Nzb29vZXM** [FireFox2000000/Moonscraper-Chart-Editor#62]
Every time i open Moonscraper on my computer (running Ubuntu 20.04.2) it throws a SDL2 InputManager error for the Start and Update functions.
![image](https://user-images.githubusercontent.com/70554251/156262887-70207db2-710d-46f2-b9d6-2e7e4de005fd.png)

**Comment by c291bGxlc3Nzb29vZXM** [comment]
Update error repeats indefinitely.

**Comment by FireFox2000000** [comment]
@bmwalters

**Comment by bmwalters** [comment]
Hey @c291bGxlc3Nzb29vZXM can you please make sure all the dependencies in the README are installed?

https://github.com/FireFox2000000/Moonscraper-Chart-Editor#runtime-dependencies-linux

I think on Ubuntu the commands to install them would be something like:

```
sudo apt update
sudo apt install ffmpeg libsdl2-2.0-0 libx11-6 libgtk-3-0
```

**Comment by c291bGxlc3Nzb29vZXM** [comment]
Already have installed Windows before you commmented but will make sure of it in my next ubuntu install
