### ISSUE TITLE
VERY high CPU and GPU usage for no reason

### ISSUE THREAD

**Issue by Schmutz02** [FireFox2000000/Moonscraper-Chart-Editor#63]
I have a 7700k and a 2070 SUPER. I don't think I should be getting these numbers at all let alone in a blank chart.

![image](https://user-images.githubusercontent.com/31942157/156979838-ea3c5e98-1c43-468e-af57-456ec6fa5363.png)

**Comment by FireFox2000000** [comment]
You probably have the framerate settings set to unlimited or a very high number. Reducing that should fix this issue.

**Comment by Schmutz02** [comment]
Ah yeah my bad. 

I don't remember changing it to unlimited, but if that's the default maybe consider setting it to something else. Also maybe move that option to the graphics tab in settings?
