### ISSUE TITLE
Settings menu overlapping

### ISSUE THREAD

**Issue by katonash** [FireFox2000000/Moonscraper-Chart-Editor#66]
When you open the Lyric Editor settings from the button on the Lyric Editor window, it opens to the Lyric Editor settings, but the Editor tab is also displayed on top of it. You have to click the Editor tab then go back to the Lyric Editor tab to fix. This happens every time you open the settings from the Lyric Editor pane.

![image](https://user-images.githubusercontent.com/30250760/163816238-f079cae4-281c-4ae3-b319-a1d6ab613ea9.png)

**Comment by TheNathannator** [comment]
Can you confirm if this is still happening? Can't seem to replicate it in the editor on my end.

**Comment by FireFox2000000** [comment]
Believe this should be fixed from a1912af1818ab93f8a44f5fc734e78671ca0ea34
