### ISSUE TITLE
Moonscraper crash on Lyric Editor threshold adjustment

### ISSUE THREAD

**Issue by katonash** [FireFox2000000/Moonscraper-Chart-Editor#67]
Moonscraper crashes if you enter a period/decimal as the first character into the "Place Threshold Time" box. 

Ex: "0.5" doesn't crash it but trying to enter ".5" does.

Log is attached.

[output_log.txt](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/files/8505978/output_log.txt)

**Comment by TheNathannator** [comment]
Can you verify if this still happens on your end? Works fine when I try it.

**Comment by FireFox2000000** [comment]
Can confirm this issue exists.

**Comment by FireFox2000000** [comment]
Fixed with commit https://github.com/FireFox2000000/Moonscraper-Chart-Editor/commit/a1912af1818ab93f8a44f5fc734e78671ca0ea34
