### ISSUE TITLE
.mid import does not treat note 103 in songs with no 116 notes as Star Power

### ISSUE THREAD

**Issue by TheNathannator** [FireFox2000000/Moonscraper-Chart-Editor#68]
Older customs made for Guitar Hero 1, 2, or 80's will get their Star Power phrases incorrectly imported as solo events due to this.

**Comment by TheNathannator** [comment]
Not sure how cleanly this can be fixed in the current system, would be easy to hack in a list to hold 103 note events temporarily until a 116 is found or the end of the song is reached but that's obviously not the best solution lol

**Comment by FireFox2000000** [comment]
Problem arises when a chart is made using only solo events but no starpower. Super super edge case and unlikely, but theoretically possible. Ideally should provide a popup to the user when this is detected to ask them to import is as a legacy chart.

**Comment by TheNathannator** [comment]
Yeah that's probably the best solution. It'll take a while to wrap my head around all of the chart parsing code, so I might tackle some smaller issues I see instead.
