### ISSUE TITLE
Opening Chart With Lyrics Wipes The Lyrics

### ISSUE THREAD

**Issue by MarshTheBacca** [FireFox2000000/Moonscraper-Chart-Editor#7]
This is on Moonscraper 1.2. I made my own chart and added lyrics, saved it, came back to change a few things and saw all the lyrics were wiped.  I had to write them all in again and I've since been using a copy of the chart to edit and then made a python program to add the lyrics from the backup into the copy that gets wiped. It's not ideal and I'm still having trouble with the python because I'm bad at it.

**Comment by FireFox2000000** [comment]
Fixed as of the v1.3 release
