### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by ghost** [FireFox2000000/Moonscraper-Chart-Editor#8]
![image](https://user-images.githubusercontent.com/40524215/52484291-dd152d80-2bad-11e9-8ed6-acd4e4bdf1e1.png)

Not sure what else to post about this, but I hope you can find out what caused it :)

Thanks

**Comment by FireFox2000000** [comment]
Will need the crash report as noted by the error message in the screenshot. Unable to do anything else otherwise.
