### ISSUE TITLE
Cannot toggle "forced" checkbox if the mouse is outside of the active note area 

### ISSUE THREAD

**Issue by FireFox2000000** [FireFox2000000/Moonscraper-Chart-Editor#80]
1. Click note tool
2. Place initial note down
3. Click on the "forced" checkbox. Note that the checkmark toggles correctly. 
4. Click on the "forced" checkbox a second time. Note that the checkmark does not turn off. (Bug)
5. Mouse into active area, and then mouse back over to the checkmark
6. Click the "forced" checkmark. Note that the checkmark toggles correctly. 
7. Click on the "forced" checkbox a second time. Note that the checkmark does not turn on. (Bug)

Note that this also occurs using the "f" key to toggle via shortcut is the mouse is outside the active view range. 
Note this also appears to occur on the "Double Kick" toggle in pro drums. 

@TheNathannator

**Comment by TheNathannator** [comment]
I can't seem to replicate this on guitar. It's only affecting drums on my end, and it's affecting all of the toggles there.

**Comment by TheNathannator** [comment]
Okay scratch the guitar part of things, stopping playback and hitting Play again in the editor made it bug out there as well.

This is a weird issue.

**Comment by TheNathannator** [comment]
I think I see the issue now, NotePropertiesPanelController.SetNewFlags() is always checking the current note when it should probably only be doing so when in the cursor tool.

**Comment by TheNathannator** [comment]
Yep, that was the problem. Will be fixed when I get a PR in for this and a couple other issues.

**Comment by FireFox2000000** [comment]
A single small PR when possible would be appreciated.
