### ISSUE TITLE
Missing default shortcut keys for "ToggleNoteAccent" and "ToggleNoteGhost" inputs

### ISSUE THREAD

**Issue by FireFox2000000** [FireFox2000000/Moonscraper-Chart-Editor#81]
DefaultControls.json

@TheNathannator

**Comment by TheNathannator** [comment]
Got any suggestions for this? I don't know which keys are available and which aren't, so I didn't worry about it at the time.

**Comment by FireFox2000000** [comment]
If you run the "InputEditor" scene you'll be able to edit and save the default controls with all the usual warnings about input conflicts as you would run the game normally. 
Note that you might hit a couple of asserts running this scene, it's a little wonky but you can ignore them.

**Comment by TheNathannator** [comment]
Good to know, thanks.

**Comment by FireFox2000000** [comment]
I'm personally not too fussed as to what the actual keys should be. "G" for ghost would have been nice but that's already taken by the global view toggle, so it's a bit of a free-for-all

**Comment by TheNathannator** [comment]
Yeah there's not much key real estate left lol, from what I can tell all that's left is `ZV,.;/[]'\789`, along with F1-F12, the numpad, and Insert/Home/End

**Comment by FireFox2000000** [comment]
They don't have to be completely unique, you can duplicate some keys as long as the input groups they're set to aren't configured to be conflicting. Just pushed up a small fix to the drums group panel inputs as well to free that up. 

Also note the SetNoteAccent and SetNoteGhost are also missing default inputs as well I've just noticed.
