### ISSUE TITLE
Mappings are not disabled when rebinding controls

### ISSUE THREAD

**Issue by TheNathannator** [FireFox2000000/Moonscraper-Chart-Editor#82]
Easiest example of this is toggling the metronome or clap while rebinding.

![image](https://user-images.githubusercontent.com/29052821/189459221-84b1745a-1b27-4e7b-b68c-5b209043537d.png)

**Comment by FireFox2000000** [comment]
Need to add a case for this under Services._IsTyping

**Comment by TheNathannator** [comment]
I'm having a difficult time understanding what exactly needs to be done. I tried doing the same thing that's done for the other component types, but that didn't work, so I'm not sure how to detect when the controls menu is open.

**Comment by TheNathannator** [comment]
Okay I got it figured out, was overthinking it a little.
