### ISSUE TITLE
Clicking "Natural" or "Cymbal"  buttons on drums group select erases dynamics flags

### ISSUE THREAD

**Issue by FireFox2000000** [FireFox2000000/Moonscraper-Chart-Editor#84]
1. Instrument drums
2. 4-lane Pro Drums
3. Place down 2 or more notes using the note tool
4. Highlight 2 or more notes with the cursor tool
5. Click "accent" button. All highlighted notes should show "accent" modifier indicator.
6. Click "cymbal" button. Note that all available notes become cymbals, but "accent" modifiers have been erased. 

Note that this current behaviour does not mirror the reverse behaviour, i.e. setting all cymbals notes to be accents does not clear cymbal flag. Therefore it's expected that accent modifiers should not be erased as setting a note as cymbal or a tom has no relation to dynamics. 

@TheNathannator

**Comment by FireFox2000000** [comment]
Side note- "Natural" button should probably be a "Tom" button instead, but I don't overly care too much about that, just something to note.

**Comment by TheNathannator** [comment]
I can see leaving Natural the way it is having some utility (since dynamics aren't the "natural" state), maybe adding a separate Tom button that doesn't affect dynamics would be good.

**Comment by TheNathannator** [comment]
I can see leaving Natural the way it is having some utility (since dynamics aren't the "natural" state), maybe adding a separate Tom button that doesn't affect dynamics would be good.

**Comment by TheNathannator** [comment]
Ended up not going with that since you had already replaced Natural lol, it's also not that hard to just make an extra click to set everything back.
