### ISSUE TITLE
Problem Exporting .MID Files

### ISSUE THREAD

**Issue by JosephOsborne** [FireFox2000000/Moonscraper-Chart-Editor#9]
It says Object reference not set to an instance of an object.

**Comment by JosephOsborne** [comment]
I am trying to add my song to Clone Hero.

**Comment by FireFox2000000** [comment]
Would you be able to provide the .chart file and what version of Moonscraper you're using so I can replicate the issue?

**Comment by JosephOsborne** [comment]
Yes.

**Comment by JosephOsborne** [comment]
https://drive.google.com/open?id=1SngWsOiSv2BZAMxOh08oVOregnzyn4EN

**Comment by FireFox2000000** [comment]
No longer an issue in the latest release.
