### ISSUE TITLE
Missing "Solo" & "Soloend"?

### ISSUE THREAD

**Issue by seasidesolitude** [FireFox2000000/Moonscraper-Chart-Editor#98]
Hey there, I was just wondering how I can add solo markers in Moonscraper. No matter which version of Moonscraper I download, I do not have the solo and soloend markers. When I type them in manually, they still don't work when playing my chart in Clone Hero. Please help? Thank you :)

**Comment by FireFox2000000** [comment]
These should already be implemented as part of the local events (red flag) tool. If these aren't present then you'll either need to do a complete uninstall and reinstall or edit your "local_events.txt" file located in the "Config" folder where you've installed MS to. These config files are not automatically updated between updates to prevent user specific configurations from being stomped, so it's possible you've upgraded from a version where the events didn't exist to one where they did and thus you didn't get the new event.
